#' History matching
#'
#' Performing history matching, in 1D, for multiple independent outputs, or for high-dimensional fields, given observations, error (co)variances and corresponding emulators, or true simulator output.
#'
#' This is a general function for history matching across a wide variety of cases. Based on what is provided (some combination of emulators, sets of inputs to calculate the implausibility at, observations, ...), it recognises whether we are in the situation of multiple independent outputs or whether a single implausibility is to be calculated.
#' 
#' The possible cases, and the expected behaviour:
#' 
#' * `Obs` is a scalar, and so `emulator` should contain only a single emulator, and the 1D implausibility is calculated via `Impl1D`
#' * `Obs` is a vector of length k, and `emulator` is a list of k emulators. Each of the k outputs is treated independently, and the 1D implausibility is calculated via `Impl1D`
#' * `Obs` is a vector of length l, and `emulator` is a list of q < l emulators. Assumes that the leading q coefficients from `DataBasis$tBasis` have been emulated, and calculates `ImplField` (efficiently via basis decomposition)
#' 
#' Other cases (e.g., emulating l outputs independently, but wishing to calculate the l-dimensional implausibility rather than l independent 1D implausibilities) require explicitly setting `Multivariate` to generate the desired behaviour.
#' 
#' The set of points at which the implausibility is to be calculated can either be provided explicitly (e.g., a space-filling prior design), or inherited from the NROY space given by a previous wave(s) of history matching.
#' 
#' This function can be used sequentially to history match across multiple waves, by providing the previous wave output (generated by running `HistoryMatch`) in `PreviousWave`. A new set of emulators (and/or observations) can be provided for the new wave.
#' 
#' Instead of providing emulators, the `TrueOutput` can be given in order to calculate the true implausibility/NROY space, obtained by running the simulator exactly (emulator variance = zero). In this case, the length of the observations and the true output should always be the same. By default, the function assumes the multivariate implausibility is desired if the dimension is at least 50, else calculates a set of 1D implausibilities. This behaviour can be overriden by setting `Multivariate`.
#'
#' @param emulator Either a single emulator, or a list of emulators, that provide predictions for the output(s) to be calibrated to. Likely an object output by `FitEmulators`. If `NULL`, `TrueOutput` must be provided instead. 
#' @param design Inputs at which to calculate the implausibility. If `NULL`, `PreviousWave` must be provided instead. In this case, the implausibility is evaluated at all inputs in the current NROY space according to `PreviousWave`.
#' @param DataBasis If the multivariate implausibility is to be calculated, then the function needs the basis that the emulated coefficients relate to. Likely an object output by `MakeDataBasis`. If `NULL`, assumes that calculating the 1D implausibility independently across emulated outputs.
#' @param Obs The observations. Can be a single value or a vector. Its length needs to either match the number of emulators (1D implausibility case), the number of columns provided in `TrueOutput`, or the dimension l of the basis vectors in `DataBasis$tBasis`.
#' @param ObsVar Observation error variance matrix. If a single value is provided, assumes the observation error is constant and uncorrelated across all outputs provided in `Obs`. In the case of l independent outputs, can be provided as a vector of length l. In the case of the multivariate implausibility, needs to be an lxl matrix.
#' @param DiscVar Discrepancy variance matrix. Defaults to zero as it is possible to set `ObsVar` as the sum of the observation error variance and the discrepancy variance, given that internally these two terms are treated independently and summed. The same rules apply as for providing `ObsVar`. 
#' @param obs_inds If the observation vector is a subset of the full output as contained in `DataBasis$tBasis`, this selects the indices from the full output that correspond to observations. Defaults to `NULL`, which corresponds to all outputs observed.
#' @param TrueOutput The actual simulator output corresponding to `design`, so that the 'true' implausibility (i.e., with the exact output and zero variance) is calculated. Defaults to `NULL`. If provided, number of columns needs to be consistent with length of `Obs`.
#' @param Multivariate Whether to calculate the k-dim implausibility (`TRUE`) or k 1D implausibilities (`FALSE`). The default is `auto`, which interprets which is desired given the provided lengths of `emulator` and `Obs`.
#' @param PreviousWave The previous wave of history matching, containing a set of points that are in the current NROY space. Should be the output of a previous evaluation of `HistoryMatch`, or contain the same fields.
#' @param ... kmax, threshold, etc.
#' 
#' @returns \item{Impl}{The implausibility for each input, corresponding to the rows of `design`. If calculating multiple 1D implausibilities, output is a matrix with the corresponding number of columns.}
#' \item{NROY}{The proportion of points that are in NROY space.}
#' \item{inNROY}{A logical vector indicating which points are in NROY space.}
#' \item{Pass_kth}{If 1D implausibility, provides the proportion of points that are in each marginal NROY, i.e. according to each observation independently.}
#' \item{Pass_N}{If 1D implausibility, provides the proportion of points that are in the marginal NROY space for N of the k provided constraints, for N=0,...k.}
#' \item{threshold}{The implausibility threshold that was used to rule out points.}
#' \item{Design}{The inputs that the implausibility was evaluated at, with a column added to indicate whether each input vector is in the current NROY space, with the wave number appended. E.g., this column is labelled 'NROY1' if `PreviousWave` was not provided. If `PreviousWave` was provided, appends 'NROYk' for current wave k, and keeps all previous NROYs.}
#' \item{Preds}{The predictions at the provided inputs, including `$Expectation` and `$Variance`. If `TrueOutput` was provided instead, returns this as the expectation, and zeros as the variance.}
#' \item{wave}{The current wave number. Set to 1 if `PreviousWave` was not provided, else adds 1 to `PreviousWave$wave`.}
#' 
#' @export
HistoryMatch <- function(emulator = NULL, design = NULL, DataBasis = NULL, Obs, ObsVar, DiscVar = 0, obs_inds = NULL, TrueOutput = NULL, Multivariate = 'auto', PreviousWave = NULL, ...){
  
  # If emulator not provided, must have been given TrueOutput, check
  if (is.null(emulator) & is.null(TrueOutput)){
    stop('Need to provide either an emulator or the true output')
  }
  
  # If provide both, also flag
  if (!(is.null(emulator)) & !(is.null(TrueOutput))){
    stop('Need to *only* provide either an emulator or the true output')
  }

  # In case a vector provided, convert to a matrix
  if (!(is.null(TrueOutput))){
    TrueOutput <- as.matrix(TrueOutput)
  }
  
  # Number of outputs to be calibrated to
  ell <- ifelse(is.null(obs_inds), length(Obs), length(obs_inds))

  # If only 1 observation, check only been given a single emulator (or single true output)
  if (ell == 1){
    if (!(is.null(emulator))){
      if (is.null(emulator$method)){
        stop('1 observation provided, but either too many emulators, or emulator in incorrect format')
      }
    }
    else {
      if (ncol(TrueOutput) > 1){
        stop('1 observation provided, but more than 1 outputs')
      }
    }
    Multivariate <- FALSE
  }
  # If more than 1 obs, we might have only a single emulator (single coefficient)
  
  # If provided Multivariate = TRUE or FALSE explicitly, check this is compatible with given object lengths
  else if (!(Multivariate == 'auto')){
    
    if (Multivariate & !(is.null(emulator))){
      if (!(length(emulator) == ell) & is.null(DataBasis)){
        stop('Mismatch between number of observations and number of emulators, or missing a DataBasis object.
              Setting Multivariate = TRUE requires one of these.')
      }
      
      if (!(length(emulator) == ell) & !(is.null(DataBasis))){
        check_name <- ifelse(ell == 1, emulator$response, emulator[[1]]$response)
        if (!(check_name %in% c('C1', 'c1', 'C_1', 'c_1'))){
          warning('Multivariate implausibility selected, DataBasis provided, and mismatch between number of observations and number of emulators.
                  Suggests basis emulation, however leading emulator not for C1 (or similar).
                  If in fact wanted independent emulation, delete DataBasis and check number of observations and emulators match.',
                  immediate. = TRUE)
        }
      }
    }
    
    else if (!(Multivariate) & !(is.null(emulator))){
      if (!(length(emulator) == ell)){
        stop('Mismatch between number of observations and number of emulators, should be identical for 1D implausibility.')
      }
    }
    
    else if (is.null(emulator)){
      if (!(ncol(TrueOutput) == ell)){
        stop('Mismatch between number of observations and number of true outputs.')
      }
    }
  }
  
  # Determine whether HM in 1D across multiple metrics, or have basis emulator
  else if (Multivariate == 'auto') {
    if (!(is.null(emulator))){
      Multivariate <- ifelse(length(emulator) == ell, FALSE, TRUE)
      if (Multivariate & is.null(DataBasis)){
        stop('Provided q emulators and ell != q observations to calibrate to. Either provide DataBasis, or ensure ell = q.')
      }
    }
    
    else {
      Multivariate <- ifelse(ncol(TrueOutput) == ell & ell < 50, FALSE, TRUE)
    }
  }

  if (is.null(design) & is.null(PreviousWave)){
    stop('Requires design if there is no PreviousWave to inherit this from.')
  }
  
  # Find wave number (for clear labelling of NROY spaces when multiple waves)
  if (is.null(PreviousWave)){
    wave <- 1
  }
  
  else {
    wave <- PreviousWave$wave + 1
  }

  # If previous HM wave provided, select points currently in NROY, and only predict for these
  if (!(is.null(PreviousWave))){
    current_nroy <- paste0('NROY',wave-1)
    nroy_inds <- which(PreviousWave$Design[,current_nroy])
    design <- PreviousWave$Design[nroy_inds,]
  }

  # Evaluate emulators at design
  if (is.null(TrueOutput)){
    preds <- Predict(emulator, design)
  }
  
  # If TrueOutput was provided, instead calculate implausibility based on truth (i.e., zero variance)
  else {
    preds <- NULL
    preds$Expectation <- TrueOutput
    preds$Variance <- 0*TrueOutput
  }
  
  # If a subset is not selected, use all outputs
  if (is.null(obs_inds) & Multivariate){
    obs_inds <- 1:ell
  }

  if (Multivariate & is.null(TrueOutput) & !(length(obs_inds) == ncol(preds$Expectation))){
    impl <- ImplField(preds, DataBasis, Obs = Obs, ObsVar = ObsVar, DiscVar = DiscVar, obs_inds = obs_inds, ...)
  }
  
  else if (Multivariate & is.null(TrueOutput) & length(obs_inds) == ncol(preds$Expectation)){
    impl <- ImplFieldIndEm(preds, Obs = Obs, ObsVar = ObsVar, DiscVar = DiscVar, ...)
  }
  
  else if (Multivariate & !(is.null(TrueOutput))){
    impl <- ImplFieldTrue(t(TrueOutput), Obs = Obs, ObsVar = ObsVar, DiscVar = DiscVar)
  }
  
  else {
    impl <- Impl(preds, Obs = Obs, ObsVar = ObsVar, DiscVar = DiscVar, ...)
  }
  
  design <- as.data.frame(design)
  new_nroy <- paste0('NROY', wave)
  design[,new_nroy] <- impl$inNROY
  
  # Combine new NROY information with previous if it exists
  if (!(is.null(PreviousWave))){
    PreviousWave$Design[,new_nroy] <- FALSE
    PreviousWave$Design[nroy_inds[impl$inNROY],new_nroy] <- TRUE
    design <- PreviousWave$Design
  }

  # If there was a previous wave, update $NROY to give accurate percentage of original space
  if (!(is.null(PreviousWave))){
    impl$NROY <- impl$NROY * PreviousWave$NROY
  }
  
  if (Multivariate){
    return(list(Impl = impl$Impl, threshold = impl$threshold, NROY = impl$NROY, inNROY = impl$inNROY,
                Design = design,
                Preds = preds,
                wave = wave))
  }
  
  else {
    return(list(Impl = impl$Impl, threshold = impl$threshold, NROY = impl$NROY, Pass_kth = impl$Pass_kth, Pass_N = impl$Pass_N, inNROY = impl$inNROY,
                Design = design,
                Preds = preds,
                wave = wave))
  }
}


#' High-dimensional implausibility
#'
#' Calculates the implausibility (for the \ell-dimensional field) for a set of predictions (expectations, variances) for basis coefficients.
#' 
#' Applies the decomposition from Salter & Williamson (2022), first calculating the constant term (difference between the observations and its basis representation), and adding the coefficient implausibility.
#'
#' @param Predictions A list containing components `$Expectation` and `$Variance`, where each provide the emulator expectation/variance for a set of inputs, where the rows contains the expectations/variances for different inputs, and the columns contain the q emulated basis vectors. The output of `Predict` can be provided here.
#' @param DataBasis Object containing the basis used in emulation (`$tBasis`), of which the first q columns should relate to the q columns of `Predictions$Expectation` and `Predictions$Variance`.
#' @param Obs The observations z, a vector of length l. Should not be centered as this happens internally if required, according to `DataBasis$EnsembleMean`.
#' @param ObsVar Observation error variance matrix. If a single value is provided, assumes the observation error is constant and uncorrelated across all outputs provided in `Obs`. In the case of l independent outputs, can be provided as a vector of length l. In the case of the multivariate implausibility, needs to be an lxl matrix.
#' @param DiscVar Discrepancy variance matrix. Defaults to zero as it is possible to set `ObsVar` as the sum of the observation error variance and the discrepancy variance, given that internally these two terms are treated independently and summed. The same rules apply as for providing `ObsVar`. 
#' @param obs_inds If the observation vector is a subset of the full output as contained in `DataBasis$tBasis`, this selects the indices from the full output that correspond to observations. Defaults to `NULL`, which corresponds to all outputs observed.
#' @param weightinv If not NULL, the inverse of W = var_err + var_disc, used for projection
#' @param BasisUncertainty Whether to include the variance from deleted basis vectors. Defaults to `TRUE`.
#' @param threshold The threshold used to define NROY space. Defaults to `NULL`, which assumes the 0.995 quantile of the chi-squared distribution with \ell degrees of freedom.
#' 
#' @returns \item{impl}{Vector of implausibilities corresponding to the rows of Expectation and Variance.}
#' \item{threshold}{The implausibility threshold T that was used to define NROY space.}
#' \item{NROY}{Proportion of parameter settings that are not ruled out.}
#' \item{inNROY}{Vector indicating whether a parameter setting is ruled out.}
#'
#' @export
ImplField <- function(Predictions, DataBasis, Obs, ObsVar, DiscVar = 0, obs_inds = NULL, weightinv = NULL, BasisUncertainty = TRUE, threshold = NULL){
  
  Expectation <- Predictions$Expectation
  Variance <- Predictions$Variance
  
  n <- nrow(Expectation) # number of prediction points
  q <- ncol(Expectation) # number of emulated vectors
  Basis <- DataBasis$tBasis[,1:q]
  ell <- nrow(Basis)

  if (!(q == ncol(Variance))){
    stop('Incorrect number of columns in Variance')
  }
  
  # If a subset is not selected, use all outputs
  if (is.null(obs_inds)){
    obs_inds <- 1:ell
  }

  # Check provided observation vector is consistent with the length of the model subset selected 
  if (!(length(Obs) == length(obs_inds))){
    stop('The observation vector is not the same length as the model output')
  }
  
  # Centre the observations (if DataBasis was centred)
  Obs <- Obs - DataBasis$EnsembleMean[obs_inds]
  
  # If provided single variance(s), assume iid
  if (length(ObsVar) == 1){
    ObsVar <- ObsVar*diag(length(obs_inds))
  }

  if (length(DiscVar) == 1){
    DiscVar <- DiscVar*diag(length(obs_inds))
  }
  
  # If provided a vector of variances, assumes uncorrelated
  if (length(ObsVar) == length(obs_inds)){
    ObsVar <- diag(ObsVar)
  }
  
  if (length(DiscVar) == length(obs_inds)){
    DiscVar <- diag(DiscVar)
  }
  
  # Check whether a vector with incorrect length has been provided
  if (is.null(nrow(ObsVar))){
    if (!(length(ObsVar) == length(obs_inds))){
      stop('Observations and observation error matrix have inconsistent dimensions')
    }
  }
  
  # If matrix provided, check has correct dimension
  else if (!(nrow(ObsVar) == length(obs_inds)) | !(ncol(ObsVar) == length(obs_inds))){
    stop('Observations and observation error matrix have inconsistent dimensions')
  }
  
  if (is.null(nrow(DiscVar))){
    if (!(length(DiscVar) == length(obs_inds))){
      stop('Observations and discrepancy variance matrix have inconsistent dimensions')
    }
  }
  
  # If matrix provided, check has correct dimension
  else if (!(nrow(DiscVar) == length(obs_inds)) | !(ncol(DiscVar) == length(obs_inds))){
    stop('Observations and discrepancy variance matrix have inconsistent dimensions')
  }

  W <- ObsVar + DiscVar
  if (is.null(weightinv)){
    weightinv <- GetInverse(W)
  }

  # Add uncertainty from discarded basis vectors?
  if (BasisUncertainty == TRUE){
    # These need to be projected in the same way that the emulated coefficients were
    if (is.null(DataBasis$Winv)){
      BasisVar <- DiscardedBasisVariance(DataBasis, q)
    }
    else {
      BasisVar <- DiscardedBasisVariance(DataBasis, q, weightinv = DataBasis$Winv)
    }
    W <- W + BasisVar[obs_inds,obs_inds] # basis variance exists over full output, but if we've got partial obs, only need these rows/columns
    weightinv <- GetInverse(W) # need to re-define W^-1 to include this extra variance, to enable fast calculation of full I(x)
  }
  
  # A faster implementation, if the full basis is still relatively small, and we are not considering a large number of points
  # if (BasisUncertainty == TRUE){
  #   # These need to be projected in the same way that the emulated coefficients were
  #   BasMinusQ <- DataBasis$tBasis[,-(1:q)]
  #   DeletedCoeffs <- Project(DataBasis$CentredField, BasMinusQ)
  #   EstVar <- apply(DeletedCoeffs, 2, var) # vector of variances for deleted vectors
  #   
  #   # Re-define basis as full basis
  #   Basis <- DataBasis$tBasis
  #   
  #   # Append columns of zeros to expectation to represent unemulated directions
  #   Expectation <- cbind(Expectation, matrix(0, ns, ncol(Basis) - q))
  #   
  #   # Append columns with variance for each deleted direction
  #   Variance <- cbind(Variance, matrix(rep(EstVar, each = ns), ns, ncol(Basis) - q))
  # }
  
  R_W <- ReconError(Obs, Basis[obs_inds,], weightinv = weightinv)
  
  # Project observations onto basis if required
  if (length(Obs) == length(obs_inds)){
    ObsProj <- Project(Obs, Basis[obs_inds,], weightinv = weightinv)
  }
  
  # Project variance matrices onto basis if required
  if (nrow(ObsVar) == length(obs_inds)){
    WProj <- ProjectVar(W, Basis[obs_inds,], weightinv = weightinv)
  }
  impl <- as.numeric(parallel::mclapply(1:n, 
                                        function(i) ImplCoeff(Expectation[i,], Variance[i,], ObsProj, WProj, 0*WProj),
                                        mc.cores = n_cores))
  impl <- impl + rep(R_W, n)
  if (is.null(threshold)){
    threshold <- stats::qchisq(0.995, length(obs_inds))
  }
  nroy <- sum(impl < threshold)/n
  inNROY <- impl < threshold

  return(list(Impl = impl, 
              threshold = threshold,
              NROY = nroy, 
              inNROY = inNROY))
}




#' High-dimensional implausibility with independent emulators
#'
#' Calculates the implausibility (for the \ell-dimensional field) for a set of predictions (expectations, variances) for each output.
#' 
#' Applies the decomposition from Salter & Williamson (2022), first calculating the constant term (difference between the observations and its basis representation), and adding the coefficient implausibility.
#'
#' @param Predictions A list containing components `$Expectation` and `$Variance`, where each provide the emulator expectation/variance for a set of inputs, where the rows contains the expectations/variances for different inputs, and the columns contain the emulated outputs. The output of `Predict` can be provided here.
#' @param Obs The observations z, a vector of length l. Should not be centered as this happens internally if required, according to `DataBasis$EnsembleMean`.
#' @param ObsVar Observation error variance matrix. If a single value is provided, assumes the observation error is constant and uncorrelated across all outputs provided in `Obs`. In the case of l independent outputs, can be provided as a vector of length l. In the case of the multivariate implausibility, needs to be an lxl matrix.
#' @param DiscVar Discrepancy variance matrix. Defaults to zero as it is possible to set `ObsVar` as the sum of the observation error variance and the discrepancy variance, given that internally these two terms are treated independently and summed. The same rules apply as for providing `ObsVar`. 
#' @param threshold The threshold used to define NROY space. Defaults to `NULL`, which assumes the 0.995 quantile of the chi-squared distribution with \ell degrees of freedom.
#' 
#' @returns \item{impl}{Vector of implausibilities corresponding to the rows of Expectation and Variance.}
#' \item{threshold}{The implausibility threshold T that was used to define NROY space.}
#' \item{NROY}{Proportion of parameter settings that are not ruled out.}
#' \item{inNROY}{Vector indicating whether a parameter setting is ruled out.}
#'
#' @export
ImplFieldIndEm <- function(Predictions, Obs, ObsVar, DiscVar = 0, threshold = NULL){
  
  Expectation <- Predictions$Expectation
  Variance <- Predictions$Variance
  
  n <- nrow(Expectation) # number of prediction points
  ell <- ncol(Expectation) # number of emulated vectors

  if (!(ell == ncol(Variance))){
    stop('Incorrect number of columns in Variance')
  }
  
  # Check provided observation vector is consistent with the length of the model subset selected 
  if (!(length(Obs) == ell)){
    stop('The observation vector is not the same length as the model predictions')
  }
  
  # If provided single variance(s), assume iid
  if (length(ObsVar) == 1){
    ObsVar <- ObsVar*diag(ell)
  }
  
  if (length(DiscVar) == 1){
    DiscVar <- DiscVar*diag(ell)
  }
  
  # If provided a vector of variances, assumes uncorrelated
  if (length(ObsVar) == ell){
    ObsVar <- diag(ObsVar)
  }
  
  if (length(DiscVar) == ell){
    DiscVar <- diag(DiscVar)
  }
  
  # Check whether a vector with incorrect length has been provided
  if (is.null(nrow(ObsVar))){
    if (!(length(ObsVar) == ell)){
      stop('Observations and observation error matrix have inconsistent dimensions')
    }
  }
  
  # If matrix provided, check has correct dimension
  else if (!(nrow(ObsVar) == ell) | !(ncol(ObsVar) == ell)){
    stop('Observations and observation error matrix have inconsistent dimensions')
  }
  
  if (is.null(nrow(DiscVar))){
    if (!(length(DiscVar) == ell)){
      stop('Observations and discrepancy variance matrix have inconsistent dimensions')
    }
  }
  
  # If matrix provided, check has correct dimension
  else if (!(nrow(DiscVar) == ell) | !(ncol(DiscVar) == ell)){
    stop('Observations and discrepancy variance matrix have inconsistent dimensions')
  }
  
  W <- ObsVar + DiscVar
  
  impl <- as.numeric(parallel::mclapply(1:n, 
                                        function(i) t(Obs - Expectation[i,]) %*% GetInverse(W + diag(Variance[i,])) %*% c(Obs - Expectation[i,]),
                                        mc.cores = n_cores))
  
  if (is.null(threshold)){
    threshold <- stats::qchisq(0.995, ell)
  }
  nroy <- sum(impl < threshold)/n
  inNROY <- impl < threshold
  
  return(list(Impl = impl, 
              threshold = threshold,
              NROY = nroy, 
              inNROY = inNROY))
}






#' Coefficient implausibility
#'
#' Calculates the coefficient implausibility for a single input vector x, given projected observations and error matrices.
#'
#' @param Expectation Length q vector with emulator expectations.
#' @param Variance Length q vector with emulator variances.
#' @param Obs Vector of projected observations, must be the same length as `Expectation` and `Variance`.
#' @param ObsVar Projected observation error variance matrix, must have dimension qxq.
#' @param DiscVar Projected discrepancy variance matrix, must have dimension qxq.
#'  
#' @returns The coefficient implausibility.
#'
#' @export
ImplCoeff <- function(Expectation, Variance, Obs, ObsVar, DiscVar){
  
  if (!(length(Expectation) == length(Variance))){
    stop('Emulator expectation and variance have different dimensions')
  }
  
  if (!(length(Expectation) == length(Obs))){
    stop('Emulator expectation and projected observations have different dimensions')
  }
  
  if (!(length(Expectation) == nrow(ObsVar))){
    stop('Emulator expectation and projected observation error matrix have different dimensions')
  }
  
  if (!(length(Expectation) == nrow(DiscVar))){
    stop('Emulator expectation and projected discrepancy matrix have different dimensions')
  }
  
  V <- ObsVar + DiscVar + diag(Variance)
  Q <- chol(V)
  proj.output <- Expectation
  y <- backsolve(Q, as.vector(Obs - proj.output), transpose = TRUE)
  impl <- crossprod(y,y)
  return(impl)
}




#' High-dimensional implausibility without an emulator
#' 
#' Calculates true implausibility of simulator output.
#'
#' @param TrueOutput A matrix containing simulator output, with rows corresponding to outputs, and columns corresponding to different simulations.
#' @param Obs The observations. Its length needs to match the number of rows of `TrueOutput`.
#' @param ObsVar Observation error variance matrix. If a single value is provided, assumes the observation error is constant and uncorrelated across all outputs provided in `Obs`.
#' @param DiscVar Discrepancy variance matrix. Defaults to zero as it is possible to set `ObsVar` as the sum of the observation error variance and the discrepancy variance, given that internally these two terms are treated independently and summed. The same rules apply as for providing `ObsVar`. 
#' @param threshold The threshold used to define NROY space. Defaults to `NULL`, which assumes the 0.995 quantile of the chi-squared distribution with \ell degrees of freedom.
#'
#' @returns \item{impl}{Vector of implausibilities corresponding to the rows of Expectation and Variance.}
#' \item{threshold}{The implausibility threshold T that was used to define NROY space.}
#' \item{NROY}{Proportion of parameter settings that are not ruled out.}
#' \item{inNROY}{Vector indicating whether a parameter setting is ruled out.}

#' @export
#'
#' @examples
ImplFieldTrue <- function(TrueOutput, Obs, ObsVar, DiscVar = 0, threshold = NULL){

  ell <- nrow(TrueOutput)
  n <- ncol(TrueOutput)
  
  if (!(ell == length(Obs))){
    stop('Observations and TrueOutput have different lengths')
  }
  
  # If provided single variance(s), assume iid
  if (length(ObsVar) == 1){
    ObsVar <- ObsVar*diag(ell)
  }
  
  if (length(DiscVar) == 1){
    DiscVar <- DiscVar*diag(ell)
  }
  
  if (!(ell == nrow(ObsVar))){
    stop('Observations and observation error matrix have inconsistent dimensions')
  }
  
  if (!(ell == nrow(DiscVar))){
    stop('Observations and discrepancy variance matrix have inconsistent dimensions')
  }
  
  tmp_inverse <- GetInverse(ObsVar + DiscVar)
  impl <- as.numeric(parallel::mclapply(1:n, 
                                        function(i) t(Obs - TrueOutput[,i]) %*% tmp_inverse %*% c(Obs - TrueOutput[,i]),
                                        mc.cores = n_cores))
  
  if (is.null(threshold)){
    threshold <- stats::qchisq(0.995, ell)
  }
  
  nroy <- sum(impl < threshold)/n
  inNROY <- impl < threshold
  
  return(list(Impl = impl, 
              threshold = threshold,
              NROY = nroy, 
              inNROY = inNROY))
}






#' Instead of calculating via coeff + recon_error, could reconstruct everything
#' Should be identical
#' For testing only
#'
#' @param Predictions 
#' @param DataBasis 
#' @param Obs 
#' @param ObsVar 
#' @param DiscVar 
ImplFieldRecon <- function(Predictions, DataBasis, Obs, ObsVar, DiscVar = 0){
  
  Expectation <- Predictions$Expectation
  Variance <- Predictions$Variance
  
  n <- nrow(Expectation)
  q <- ncol(Expectation)
  ell <- nrow(DataBasis$tBasis)
  
  if (!(q == ncol(Variance))){
    stop('Incorrect number of columns in Variance')
  }
  
  # If provided single variance(s), assume iid
  if (length(ObsVar) == 1){
    ObsVar <- ObsVar*diag(ell)
  }
  
  if (length(DiscVar) == 1){
    DiscVar <- DiscVar*diag(ell)
  }
  
  if (!(ell == nrow(ObsVar))){
    stop('Observations and observation error matrix have inconsistent dimensions')
  }
  
  if (!(ell == nrow(DiscVar))){
    stop('Observations and discrepancy variance matrix have inconsistent dimensions')
  }
  
  BasisVar <- DiscardedBasisVariance(DataBasis, q)
  
  Impl <- rep(NA, n)
  for (i in 1:n){
    recon_mean <- Recon(Expectation[i,], DataBasis$tBasis[,1:q]) + DataBasis$EnsembleMean
    recon_var <- DataBasis$tBasis[,1:q] %*% diag(Variance[i,]) %*% t(DataBasis$tBasis[,1:q])
    Impl[i] <- t(Obs - recon_mean) %*% solve(recon_var + ObsVar + DiscVar + BasisVar) %*% c(Obs - recon_mean)
  }
  
  return(Impl)
}






#' Setting discrepancy multiple
#'
#' Scaling the discrepancy to ensure that the observations won't be ruled out
#'
#' @param Basis full basis
#' @param q where the basis is truncated
#' @param obs observations
#' @param level quantile of the chi-squared distribution to use (< 0.995)
#' @param weightinv inverse of W, to use in projection
#'  
#' @returns scalar to be used as discrepancy multiplier, to ensure observations not ruled out
#'
#' @export
SetDiscrepancy <- function(Basis, q, obs, level = 0.95, weightinv = NULL){
  TruncatedError <- ReconError(obs, Basis[,1:q], weightinv = weightinv)
  ell <- dim(Basis)[1]
  b <- stats::qchisq(level, ell)
  DiscMultiplier <- c(TruncatedError / b)
  return(DiscMultiplier)
}


#' Adding discarded basis variance
#' 
#' Function that gives variance given by deleted basis vectors (Wilkinson 2010), used within HistoryMatch
#' 
#' @param DataBasis - object containing basis, centred field etc.
#' @param q - where the basis is truncated
#' @param weightinv inverse of W, to use in projection
#' 
#' @returns Matrix containing uncertainty due to basis truncation
#' 
#' @export
DiscardedBasisVariance <- function(DataBasis, q, weightinv = NULL){
  BasMinusQ <- DataBasis$tBasis[,-(1:q)]
  DeletedCoeffs <- Project(DataBasis$CentredField, BasMinusQ, weightinv)
  EstVar <- apply(DeletedCoeffs, 2, stats::var)
  DeletedBasisVar <- BasMinusQ %*% diag(EstVar) %*% t(BasMinusQ)
  return(DeletedBasisVar)
}

#' kth max implausibility
#' 
#' Calculating the kth max value across a vector.
#'
#' @param x A vector.
#' @param k Which maximum to find.
#'
#' @returns The kth maximum.
#' @export
#'
#' @examples
kth_max <- function(x,k) {
  sorted_values <- sort(x, decreasing = TRUE)
  sorted_values[k]
}


#' Marginal NROY
#' 
#' How many inputs pass the kth constraint.
#'
#' @param impl Matrix of implausibilities, with each row corresponding to an input vector, and each column corresponding to an output.
#' @param threshold Threshold to use for defining NROY space. Defaults to 3.
#'
#' @returns Proportion of inputs that are in NROY according to each of the given outputs.
#' @export
#'
#' @examples
pass_kth_metric <- function(impl, threshold = 3){
  ns <- nrow(impl)
  apply(impl < threshold, 2, sum) / ns
}

#### RENAME? pass_by_run? ####
#' Number of constraints satisfied.
#' 
#' How many inputs pass N/k constraints.
#'
#' @param impl Matrix of implausibilities, with each row corresponding to an input vector, and each column corresponding to an output.
#' @param threshold Threshold to use for defining NROY space. Defaults to 3.
#'
#' @returns Proportion of inputs that satisfy N = 0,1,...k of the k constraints.
#' @export
#'
#' @examples
pass_metric <- function(impl, threshold = 3){
  ns <- nrow(impl)
  summary(as.factor(apply(impl < threshold, 1, sum, na.rm = TRUE))) / ns
}



#' 1D implausibility
#'
#' Calculates the 1D implausibility for 1 or more metrics
#'
#' @param Predictions A list containing components `$Expectation` and `$Variance`, where each provide the emulator expectation/variance for a set of inputs, where the rows contains the expectations/variances for different inputs, and the columns contain different outputs. The output of `Predict` can be provided here.
#' @param Obs The observations. Can be a single value or a vector. Its length needs to match the number of columns in `Predictions$Expectations`.
#' @param ObsVar Observation error variance. If a single value is provided, assumes the observation error is constant and uncorrelated across all outputs provided in `Obs`. Else should be a vector with the same length as `Obs`.
#' @param DiscVar Discrepancy variance. Defaults to zero as this may be included in `ObsVar`. The same rules apply as for providing `ObsVar`. 
#' @param kmax Which kth-max implausibility to use to define NROY space. Defaults to 1 (i.e. use the maximum implausibility across all outputs to classify an input).
#' @param threshold Threshold to use for defining NROY space. Defaults to 3.
#'
#' @returns \item{Impl}{The implausibility for each input, corresponding to the rows of `design`. If calculating multiple implausibilities, output is a matrix with the corresponding number of columns.}
#' \item{threshold}{The implausibility threshold T that was used to define NROY space.}
#' \item{NROY}{The proportion of points that are in NROY space.}
#' \item{inNROY}{A logical vector indicating which points are in NROY space.}
#' \item{Pass_kth}{The proportion of points that are in each marginal NROY, i.e. according to each observation independently.}
#' \item{Pass_N}{The proportion of points that are in the marginal NROY space for N of the k provided constraints, for N=0,...k.}
#'
#' @export
Impl <- function(Predictions, Obs, ObsVar, DiscVar = 0, kmax = 1, threshold = 3){

  Expectation <- Predictions$Expectation
  Variance <- Predictions$Variance
  
  # Number of outputs
  ell <- ncol(Expectation)
  
  # Number of prediction points
  n <- nrow(Expectation)

  if (is.null(ell)){
    ell <- 1
  }
  
  if (!(length(Obs) == ell)){
    stop('Inconsistency between number of emulator predictions and number of observations provided')
  }
  
  if (!(length(ObsVar) %in% c(1,ell))){
    stop('Inconsistency between number of emulator predictions and number of observation error variances provided')
  }
  
  if (length(ObsVar) == 1 & !(ell == 1)){
    ObsVar <- rep(ObsVar, ell)
  }
  
  if (!(length(DiscVar) %in% c(1,ell))){
    stop('Inconsistency between number of emulator predictions and number of discrepancy variances provided')
  }
  
  if (length(DiscVar) == 1 & !(ell == 1)){
    DiscVar <- rep(DiscVar, ell)
  }
  
  # Converting to vector
  Obs <- as.numeric(Obs)
  
  # Calculate implausibility
  impl <- parallel::mclapply(1:ell, 
                             function(k) Impl1D(Expectation[,k], Variance[,k], Obs[k], ObsVar[k], DiscVar[k]),
                             mc.cores = n_cores)
  impl <- matrix(unlist(impl), n, ell)

  # Proportion of samples that pass each metric individually
  pass_kth <- pass_kth_metric(impl, threshold)
  
  # Number of constraints passed by each sample
  pass_N <- pass_metric(impl, threshold)
  
  # Defining NROY based on kmax
  impl_kmax <- apply(impl, 1, kth_max, k = kmax)
  nroy <- mean(impl_kmax < threshold)
  inNROY <- impl_kmax < threshold

  return(list(Impl = impl,
              threshold = threshold,
              NROY = nroy,
              Pass_kth = pass_kth,
              Pass_N = pass_N,
              inNROY = inNROY))
}






#' Title
#'
#' @param expectation 
#' @param variance 
#' @param Obs 
#' @param ObsVar 
#' @param DiscVar 
#'
#' @returns
#'
#' @examples
Impl1D <- function(expectation, variance, Obs, ObsVar, DiscVar = 0){
  abs(expectation - Obs) / sqrt(variance + ObsVar + DiscVar)
}






#' Generate a design in NROY
#' 
#' Given a set of points in the current NROY space (or otherwise), finds a space-filling sample of a given size.
#'
#' @param CandidatePoints A matrix of input vectors to select the new design from. Each row corresponds to different points, each column to different input dimensions.
#' @param n_new The size of the new design.
#' @param reps How many sample designs to assess. Defaults to 100.
#'
#' @returns \item{design}{The selected space-filling design.}
#' \item{inds}{Indices relating to which rows of `CandidatePoints` were selected.}
#' 
#' @export
#'
#' @examples
NewDesign <- function(CandidatePoints, n_new, reps = 100){
  
  # If final column(s) of CandidatePoints are NROY indicator, remove
  nroy_inds <- grep('NROY', colnames(CandidatePoints))
  
  if (length(nroy_inds) > 0){
    CandidatePoints <- CandidatePoints[,-nroy_inds]
  }
  
  # Generate candidate designs of size n_new
  inds_list <- NULL
  dist_min <- numeric(reps)
  for (i in 1:reps){
    inds_list[[i]] <- sample(1:nrow(CandidatePoints), n_new)
    tmp_design <- CandidatePoints[inds_list[[i]],]
    dists <- fields::rdist(tmp_design)
    diag(dists) <- NA
    dist_min[i] <- min(c(dists), na.rm = TRUE)
    rm(dists)
  }
  
  k <- which.max(dist_min)
  
  new_design <- CandidatePoints[inds_list[[k]],]
  
  rownames(new_design) <- NULL
  
  return(list(design = new_design,
              inds = inds_list[[k]]))
}




#' Include NROY points from previous waves
#' 
#' At wave k > 1, add any points from previous waves that are in the current NROY space, and define the new DataBasis object and centred observations by adding these to the new ensemble
#' 
#' @param DesignHM output from running PredictAndHM over the old design
#' @param NewDesign new inputs
#' @param NewData output corresponding to NewDesign
#' @param DataBasis object from previous wave
#' @param Obs centred observation from previous wave
#' 
#' @returns \item{Design}{Design with new wave, followed by any NROY runs from previous waves}
#' \item{DataBasis}{Basis, centred data, and ensemble mean for the new ensemble combined with previous NROY runs}
#' \item{Obs}{Centred observations, given new ensemble mean} 
#' 
#' @export
# AddPreviousNROY <- function(DesignHM, NewDesign, NewData, DataBasis, Obs, ...){
#   NROYinds <- which(DesignHM$inNROY == TRUE)
#   FullDesign <- rbind(NewDesign, DesignHM$Design[NROYinds,])
#   OldRawData <- DataBasis$CentredField[,NROYinds] + DataBasis$EnsembleMean
#   RawObs <- Obs + DataBasis$EnsembleMean
#   AllData <- cbind(NewData, OldRawData)
#   NewDataBasis <- MakeDataBasis(data = AllData, RemoveMean = TRUE, ...)
#   NewObs <- RawObs - NewDataBasis$EnsembleMean
#   return(list(Design = FullDesign, DataBasis = NewDataBasis, Obs = NewObs))
# }



#' Plotting NROY space
#' 
#' Pairs plots and 1D densities of NROY space
#'
#' @param Design Data frame of inputs, possibly with a TRUE/FALSE final column named `NROY`.
#' @param k Indices relating to which columns of `Design` to plot. If NULL, plots all.
#' @param NROY Vector of TRUE/FALSE labels, corresponding to rows of `Design`. If NULL, uses the final column of `Design`.
#' @param Impl Vector of implausibility values, corresponding to rows of `Design`. If provided, the lower pairs plots are coloured by implausibility instead of by whether points are in NROY. Defaults to `NULL`.
#' @param Truth A point in input space to be added to the pairs plots, perhaps representing a known true input value, or a default setting. Defaults to NULL, in which case no point is added.
#'
#' @returns Pairs plot.
#' @export
#'
#' @examples
PlotNROY <- function(Design, k = NULL, NROY = NULL, Impl = NULL, Truth = NULL){
  # If a vector of NROY labels is not provided, assume this is the final column of Design
  if (is.null(NROY)){
    colnames(Design)[ncol(Design)] <- 'NROY'
  }
  
  else {
    if (!(length(NROY) == nrow(Design))){
      stop('Length of provided NROY labels is different from number of rows in Design')
    }
    Design <- data.frame(Design, NROY = NROY)
  }
  
  # If columns to be plotted aren't provided, use all prior to the final column
  if (is.null(k)){
    k <- 1:(ncol(Design)-1)
  }
  
  # If Impl is provided, colour points with this instead
  if (!(is.null(Impl))){
    if (!(length(Impl) == nrow(Design))){
      stop('Length of provided implausibilities is different from number of rows in Design')
    }
    Design$NROY <- Impl
  }

  size <- ifelse(nrow(Design) < 1000, 2, 0.5)
  
  # If only 2 inputs provided, single pairs plot
  if (length(k) == 2){
    Design$input1 <- Design[,k[1]]
    Design$input2 <- Design[,k[2]]
    
    plot <- ggplot(Design, aes(.data$input1, .data$input2, col = .data$NROY)) + 
      geom_point(size = size) +
      labs(x = colnames(Design)[k[1]], y = colnames(Design)[k[2]]) +
      theme_bw()
    
    if (is.null(Impl)){
      plot <- plot + scale_color_manual(values = cols_validate[-1])
    }
    else {
      plot <- plot + viridis::scale_color_viridis()
    }

    if (!is.null(Truth)){
      Truth <- as.data.frame(Truth)
      Truth$input1 <- Truth[,k[1]]
      Truth$input2 <- Truth[,k[2]]
      plot <- plot + geom_point(data = Truth, col = 'red', shape = 17, size = 4)
    }
  }
  
  else {
    if (is.null(Impl)){
      plot <- GGally::ggpairs(Design, columns = k, aes(col = .data$NROY), 
                              upper = list(continuous = GGally::wrap("density", alpha = 0.5), combo = "box_no_facet"),
                              lower = list(continuous = GGally::wrap("points", alpha = 0.3, size = size), combo = GGally::wrap("dot_no_facet", alpha = 0.4)),
                              diag = list(continuous = GGally::wrap("densityDiag", alpha = 0.3)), 
                              legend = c(1,1)) +
        theme_bw() +
        theme(legend.position = "bottom") + 
        scale_fill_manual(values = cols_validate[-1]) + 
        scale_color_manual(values = cols_validate[-1])
    }

    else {
      plot <- GGally::ggpairs(Design, columns = k, aes(col = .data$NROY, fill = .data$NROY<3), 
                              upper = list(continuous = GGally::wrap("points", alpha = 0.3, size = size), combo = GGally::wrap("dot_no_facet", alpha = 0.4)),
                              lower = list(continuous = GGally::wrap("points", alpha = 0.3, size = size), combo = GGally::wrap("dot_no_facet", alpha = 0.4)),
                              diag = list(continuous = GGally::wrap("densityDiag", alpha = 0.3)),
                              legend = c(2,1)) +
        theme_bw() +
        theme(legend.position = "bottom") + 
        labs(col = 'Implausibility') +
        scale_fill_manual(values = cols_validate[-1], guide = 'none') + 
        viridis::scale_color_viridis()
    }

    # Add truth
    if (!is.null(Truth)){
      Truth$NROY <- NA
      for (i in 2:length(k)){
        for (j in 1:(i-1)){
          tmp <- Truth
          tmp$input1 <- Truth[,k[j]]
          tmp$input2 <- Truth[,k[i]]
          p1 <- GGally::getPlot(plot, i, j) + geom_point(data = tmp, aes(x = .data$input1, y = .data$input2), col = 'red', shape = 17, size = 4)
          plot <- GGally::putPlot(plot, p1, i, j)
          p2 <- GGally::getPlot(plot, j, i) + geom_point(data = tmp, aes(x = .data$input2, y = .data$input1), col = 'red', shape = 17, size = 4)
          plot <- GGally::putPlot(plot, p2, j, i)
        }
      }
    }
  }
  return(plot)
}









#### NOT EDITED ####

# PlotEmulator <- function(impl, design, variance = FALSE){
#   thetapred <- unit_to_theta(impl[,c('X1','X2')])
#   impl$lambda <- thetapred$lambda
#   impl$C <- thetapred$C
#   
#   if (!(is.null(dim(design)))){
#     design <- unit_to_theta(design)
#   }
#   
#   if (variance){
#     plot <- ggplot(impl, aes(lambda, C, col = Var)) + 
#       geom_point() +
#       geom_point(data = data.frame(C = design$C, lambda = design$lambda), col = 'black', size = 5, shape = 15) +
#       scale_colour_viridis_c(option = 'H') +
#       theme_minimal(base_size = 14) +
#       theme(panel.grid.minor = element_blank(), strip.text = element_text(face = "bold"))
#   }
#   
#   else{
#     plot <- ggplot(impl, aes(lambda, C, col = Mean)) + 
#       geom_point() +
#       geom_point(data = data.frame(C = design$C, lambda = design$lambda), col = 'black', size = 5, shape = 15) +
#       scale_colour_viridis_c() +
#       theme_minimal(base_size = 14) +
#       theme(panel.grid.minor = element_blank(), strip.text = element_text(face = "bold"))
#   }
#   
#   return(plot)
# }
