# Load train/val inds
train_inds <- readRDS("papers/raikoke/data/train_inds.rds")
val_inds <- readRDS("papers/raikoke/data/val_inds.rds")

# Load input/output for each time point
# These objects contain the 1000 runs, where
# - each input has been scaled to [-1,1]
# - noise is a uniformly, randomly sampled term on [-1,1] to protect against overfitting mean functions
# - LogTotal is the log of the total ash for the given timepoint/region
tDataT3 <- readRDS("papers/raikoke/data/tDataT3.rds")
tDataT5 <- readRDS("papers/raikoke/data/tDataT3.rds")
tDataT7 <- readRDS("papers/raikoke/data/tDataT3.rds")

# Also for each region
# R1 = N, R2 = S, R3 = W, R4 = E, R5 = NW, R6 = NE, R7 = SE, R8 = SW
# When given in a list of 8 objects, this is the order
# Sometimes objects will have Rx in the name, where x relates to the above numbering
tData_regions <- readRDS("papers/raikoke/data/tDataT3.rds")


#### Fitting emulators ####
# Emulators for totals at T3, T5 and T7 are available in data folder
# Here uses MOGP, but other choices (e.g. RobustGasp) should do fine
# Key assumption we make is that first fit a (possibly complex) mean function to explain variability
# This process also selects active/inactive variables prior to fitting covariance



#### Loading emulators ####
# Either generated by above code, or loading directly from file
EmT3 <- load_ExUQmogp('papers/raikoke/data/EmT3')
EmT5 <- load_ExUQmogp('papers/raikoke/data/EmT5')
EmT7 <- load_ExUQmogp('papers/raikoke/data/EmT7')

EmT3_MET <- LoadMulti('papers/raikoke/data/EmT3_MET')
EmT5_MET <- LoadMulti('papers/raikoke/data/EmT5_MET')
EmT7_MET <- LoadMulti('papers/raikoke/data/EmT7_MET')

#### Validation ####
# These are unlikely to be automatically suitable - likely need to revisit some emulator assumptions above
ValT3 <- ValidateBoth(EmT3, EmT3_MET, tDataT3, design[,-4], train_inds, val_inds, train_inds, val_inds)
ValT3$plot1

ValT5 <- ValidateBoth(EmT5, EmT5_MET, tDataT5, design[,-4], train_inds, val_inds, train_inds, val_inds)
ValT5$plot1

ValT7 <- ValidateBoth(EmT7, EmT7_MET, tDataT7, design[,-4], train_inds, val_inds, train_inds, val_inds)
ValT7$plot1

# Above function plots, reports % in 95% prediction interval
# Could also consider other metrics, e.g. compare RMSE between the 2 sets of emulators
rmserr(ValT3$overall$Mean, ValT3$overall$Truth)$rmse
rmserr(ValT3$met$Mean, ValT3$met$Truth)$rmse

rmserr(ValT5$overall$Mean, ValT5$overall$Truth)$rmse
rmserr(ValT5$met$Mean, ValT5$met$Truth)$rmse

rmserr(ValT7$overall$Mean, ValT7$overall$Truth)$rmse
rmserr(ValT7$met$Mean, ValT7$met$Truth)$rmse

# Repeat for all regions








